stages:
- test
- build
- deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/SAST-IaC.latest.gitlab-ci.yml

build-api:
  stage: build
  services:
  - docker:dind
  before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
  - cd api/
  - docker build --pull -t "$REGISTRY/api/goxor_store-api" .
  - docker push "$REGISTRY/api/goxor_store-api"
  rules:
  - if: $CI_COMMIT_BRANCH == "main"
    exists:
    - docker-compose.yml
    changes:
    - api/**/*
    - api/*
    - docker-compose.yml
    - .gitlab-ci.yml

build-web:
  stage: build
  services:
  - docker:dind
  before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
  - cd web/
  - docker build --pull -t "$REGISTRY/website/goxor_store-website" .
  - docker push "$REGISTRY/website/goxor_store-website"
  rules:
  - if: $CI_COMMIT_BRANCH == "main"
    exists:
    - docker-compose.yml
    changes:
    - web/**/*
    - web/*
    - docker-compose.yml
    - .gitlab-ci.yml

deploy-job:
  stage: deploy
  before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
  - docker-compose -f 'docker-compose.yml' --project-name 'w-gxrstr' down
  - docker-compose -f 'docker-compose.yml' --project-name 'w-gxrstr' up -d
  rules:
  - if: $CI_COMMIT_BRANCH == "main"
    exists:
    - docker-compose.yml
    changes:
    - api/**/*
    - api/*
    - web/**/*
    - web/*
    - docker-compose.yml
    - .gitlab-ci.yml
