stages:
  - test
  - build
  - deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/SAST-IaC.latest.gitlab-ci.yml

docker-build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
    - cd api/
    - docker build --pull -t "$REGISTRY/api/goxor_store-api" .
    - docker push "$REGISTRY/api/goxor_store-api"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - api/Dockerfile

deploy-job:
  stage: deploy
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
    - cd api/
    - docker-compose -f 'docker-compose.yml' --project-name 'w-gxrstr' down
    - docker-compose -f 'docker-compose.yml' --project-name 'w-gxrstr' up -d
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - api/docker-compose.yml
