stages:
  - test
  - build
  - deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/SAST-IaC.latest.gitlab-ci.yml

docker-build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
    - cd api/
    - docker build --pull -t "$REGISTRY/api/goxor_store-api" .
    - docker push "$REGISTRY/api/goxor_store-api"
    - cd ../web
    - docker build --pull -t "$REGISTRY/website/goxor_store-website" .
    - docker push "$REGISTRY/website/goxor_store-website"
  only:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - docker-compose.yml
      changes:
        - api/*
        - web/*
        - docker-compose.yml

deploy-job:
  stage: deploy
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
    - docker-compose -f 'docker-compose.yml' --project-name 'w-gxrstr' down
    - docker-compose -f 'docker-compose.yml' --project-name 'w-gxrstr' up -d
  only:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - docker-compose.yml
      changes:
        - api/*
        - web/*
        - docker-compose.yml
