version: "3"

services:
  web:
    image: registry.vapronva.pw/api/goxor_store-api:latest
    restart: always
    container_name: "web_api-goxor_store"
    environment:
      - IPINFO_TOKEN=${IPINFO_TOKEN}
      - YANDEXCLOUD_FOLDERID=${YANDEXCLOUD_FOLDERID}
      - YANDEXCLOUD_APITOKEN=${YANDEXCLOUD_APITOKEN}
      - VIRTUAL_HOST=api.goxor.store
      - VIRTUAL_PORT=8000
    user: 1005:1006
    networks:
      - "w-gxrstr-network"
    volumes:
      - goxorstoreaudiostorage:/usr/src/app/user-audios
  app_web:
    image: registry.vapronva.pw/website/goxor_store-website:latest
    restart: unless-stopped
    container_name: "web-goxor_store"
    user: 1005:1006
    networks:
      - "w-gxrstr-network"
    environment:
      - VIRTUAL_HOST=goxor.store
      - VIRTUAL_PORT=8000

volumes:
  goxorstoreaudiostorage:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.75.10,rw,noatime,nolock,soft,rsize=8192,wsize=8192,tcp,timeo=15
      device: "192.168.75.10:/mnt/seagate-4tb-ex7-ws221yth/goxor_store/user-audios"

networks:
  w-gxrstr-network:
    external: true
